
#' The \code{calendars} vector contains all calendar identifiers.
#'
#' @name calendars
#' @docType data
#' @keywords data
#' @examples
#' head(calendars, 10)
NULL

calendars <- c("TARGET",
               "UnitedStates",
               "UnitedStates/LiborImpact",
               "UnitedStates/NYSE",
               "UnitedStates/GovernmentBond",
               "UnitedStates/NERC",
               "UnitedStates/FederalReserve",
               "UnitedStates/SOFR",
               "Argentina",
               "Australia",
               "Australia/ASX",
               "Austria",
               "Austria/Exchange",
               "Bespoke",
               "Botswana",
               "Brazil",
               "Brazil/Exchange",
               "Canada",
               "Canada/TSX",
               "Chile",
               "China",
               "China/IB",
               "Croatia",
               "CzechRepublic",
               "Denmark",
               "Finland",
               "France",
               "France/Exchange",
               "Germany",
               "Germany/FrankfurtStockExchange",
               "Germany/Xetra",
               "Germany/Eurex",
               "Germany/Euwax",
               "HongKong",
               "Hungary",
               "Iceland",
               "India",
               "Indonesia",
               "Israel",
               "Israel/TASE",
               "Israel/SHIR",
               "Israel/Telbor",
               "Italy",
               "Italy/Exchange",
               "Japan",
               "Malta",
               "Mexico",
               "Montenegro",
               "NewZealand",
               "NewZealand/Auckland",
               "NorthMacedonia",
               "Norway",
               "Null",
               "Poland",
               "Romania",
               "Russia",
               "SaudiArabia",
               "Serbia",
               "Singapore",
               "Slovakia",
               "Slovenia",
               "SouthAfrica",
               "SouthKorea",
               "SouthKorea/KRX",
               "Sweden",
               "Switzerland",
               "Taiwan",
               "Thailand",
               "Turkey",
               "Ukraine",
               "UnitedKingdom",
               "UnitedKingdom/Exchange",
               "UnitedKingdom/Metals",
               "Uzbekistan",
               "WeekendsOnly")
