# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: ci

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"
  CCACHE_BASEDIR: ${{ github.workspace }} # Rewrites absolute paths to relative paths
#  CCACHE_DIR: ${{ github.workspace }}/.ccache # Explicit local storage for Github caching

jobs:
  ci:
    strategy:
      matrix:
        include:
          #- {os: macOS-latest}
          - {os: ubuntu-latest}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup
        uses: eddelbuettel/github-actions/r-ci@master

      #- name: Setup ccache for R
      #  uses: eddelbuettel/github-actions/ccache-with-R@master
      - name: Get ccache
        uses: hendrikmuhs/ccache-action@v1.2.23
        with:
          key: ccache_file
          restore-keys: ccache_file
          append-timestamp: true
          variant: ccache
          max-size: 10G # Github has a 10GB repo cache limit
          verbose: 2

      - name: Configure ccache for R
        shell: bash
        run: |
          ./ccache_setup.sh
          ccache -p
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Dependencies
        run: ./run.sh install_deps

      - name: ccache 1
        run: |
          ccache -z
          ccache -p

      - name: Test
        run: ./run.sh run_tests

      - name: ccache 2
        run: |
          ccache -s
          ccache -z

      - name: Test again, for good measure
        run: ./run.sh run_tests

      - name: ccache 3
        run: |
          ccache -s

      #- name: Coverage
      #  if: ${{ matrix.os == 'ubuntu-latest' }}
      #  run: ./run.sh coverage
